[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "timeclock"
version = "0.0.1"
authors = [
  { name="Kai Amann", email="kai.amann@fau.de" },
]
description = "A tool for tracking working hours."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[project.scripts]
timeclock = "timeclock.cli:run"

[project.urls]
"Homepage" = "https://github.com/kaiamann/TimeClock"
"Bug Tracker" = "https://github.com/kaiamann/TimeClock/issues"